server:
  port: 7002

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${username}
    password: ${password}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: account-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka